# Generated by Django 3.1.2 on 2020-11-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0002_bookinfo_heroinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
