# Generated by Django 3.0.8 on 2021-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0003_auto_20201102_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_pic', models.ImageField(upload_to='kdapp')),
            ],
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table=None,
        ),
    ]
