# Generated by Django 3.0.8 on 2021-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=254)),
                ('api_url', models.CharField(max_length=254)),
                ('api_method', models.CharField(max_length=254)),
                ('api_params', models.CharField(max_length=254)),
                ('api_dsc', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'apiinfo',
            },
        ),
    ]
