# Generated by Django 3.0.8 on 2021-10-12 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KdTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_info',
            name='api_creat_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='api_info',
            name='api_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
